### ISSUE TITLE
support for RSA functions

### ISSUE THREAD

**Issue by jleni** [LedgerHQ/speculos#106]
Functions such as `cx_rsa_generate_pair` are not supported

**Comment by Saltari** [comment]
With the integration of the 2.0 SDK speculos now embeds the crypto binary of the 2.0 version (with most of the crypto direct calls)
Therefore all the RSA functions can now be run from speculos on target nanos 2.0
The problem remains on LNX (1.3/1.2) but will disappear soon with the next firmware update.
