### ISSUE TITLE
No crash on unaligned pointer access

### ISSUE THREAD

**Issue by shufps** [LedgerHQ/speculos#108]
I'm not sure if this is a speculos problem or if it actually can be solved at all ...

On real hardware the microcontroller crashes on unaligned pointer accesses, speculos doesn't care.

This make debugging quite hard because outcome of tests can diverge (Ok when run in speculos, Crash when run on real hardware).

Would be nice if this could be fixed (if even possible).

**Comment by greenknot** [comment]
Unfortunately, it isn't possible. Related issue and discussion: https://github.com/LedgerHQ/speculos/issues/60 (feel free to re-open that issue if you have additional ideas.)
