### ISSUE TITLE
class APDU is defined twice in api

### ISSUE THREAD

**Issue by niooss-ledger** [LedgerHQ/speculos#215]
There are two `class APDU` in `speculos/api/api.py`: https://github.com/LedgerHQ/speculos/blob/c2c6ccd4fd06e21623c8c2d704e6b8b3084ea268/speculos/api/api.py#L180-L184 and https://github.com/LedgerHQ/speculos/blob/c2c6ccd4fd06e21623c8c2d704e6b8b3084ea268/speculos/api/api.py#L215-L218

One of them should be renamed.

**Comment by kingofpayne** [comment]
In that case we may also rename one of the two `Events` classes as well:
https://github.com/LedgerHQ/speculos/blob/c2c6ccd4fd06e21623c8c2d704e6b8b3084ea268/speculos/api/api.py#L23-L29
and
https://github.com/LedgerHQ/speculos/blob/c2c6ccd4fd06e21623c8c2d704e6b8b3084ea268/speculos/api/api.py#L138-L142

For both `Events` and `APDU`, the first class declaration is not supposed to be used externally. Nonetheless I agree it may avoid confusion having different names.
