### ISSUE TITLE
speculos client may not close speculos instance properly

### ISSUE THREAD

**Issue by kingofpayne** [LedgerHQ/speculos#243]
Current speculos client library requires the user to explicitly call the method `stop` to kill running speculos instance. This is a problem for two main reasons:
- the library user may simply forget to do this call,
- an exception may terminate the program without calling the `stop` method.

To circumvent this, a hack has been added
https://github.com/LedgerHQ/speculos/blob/master/speculos/client.py#L188-L189

However, there is no guarantee on the order of cleanup performed by Python when the program terminates, and this call may fail if some used variables (such as the `logger` global variable) are destroyed before `__del__` is called. Here is an example of crash log:

    Exception ignored in: <function SpeculosInstance.__del__ at 0x7fda292da0d0>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/speculos/client.py", line 195, in __del__
      File "/usr/local/lib/python3.8/dist-packages/speculos/client.py", line 174, in stop
      File "/usr/lib/python3.8/logging/__init__.py", line 1731, in __repr__
    TypeError: 'NoneType' object is not callable

Maybe the right solution would be to use the `with` semantic of Python to start speculos on `__enter__` and stop it on `__exit__`. This would require modifying slightly the `SpeculosClient` class to support this.

**Comment by lpascal-ledger** [comment]
This issue has been addressed by @kingofpayne with its PR #244.
