### ISSUE TITLE
How do we set "SPECULOS_SEED"?

### ISSUE THREAD

**Issue by tim-eucalyptus** [LedgerHQ/speculos#321]
It's is set at <https://github.com/LedgerHQ/speculos/blob/c0311aef48412e40741a55f113939469da78e8e5/src/bolos/os_bip32.c#L513>. Is this something we set in the Makefile of the app? What is the default in Speculos BTW?

**Comment by greenknot** [comment]
The seed can either bet passed as an argument (`./speculos.py --seed`) or through the environment variable `SPECULOS_SEED`. The default seed is [explicitly defined a few lines above](https://github.com/LedgerHQ/speculos/blob/c0311aef48412e40741a55f113939469da78e8e5/src/bolos/os_bip32.c#L24-L26).

Please follow these [instructions](https://github.com/LedgerHQ/speculos#are-you-developing-a-nano-app-as-an-external-developer) for support:

- Follow the developers documentation on the [Developer Portal](https://developers.ledger.com/docs/nano-app/introduction/) and 
- [Go on Discord](https://developers.ledger.com/discord-pro/) to chat with developer support and the developer community.
