### ISSUE TITLE
Unable to connect to VNC server using MacOS Screen Sharing application

### ISSUE THREAD

**Issue by DCRichards** [LedgerHQ/speculos#34]
## Issue
Connecting to the VNC server from MacOS Screen Sharing app hangs and does not connect.

![Screenshot 2020-03-06 at 13 08 26](https://user-images.githubusercontent.com/3857210/76088686-5bf6b880-5fb0-11ea-8959-0d2a9a738f5b.png)

## Replication

1. Start the server by running `docker-compose up` with the default options
2. Open **Screen Sharing** and attempt to connect to `vnc://localhost:41000`
3. Asks for a password, hit enter with no password
4. Hangs with no output

## System Info

* MacOS 10.14.6
* Docker 2.2.0.3

## Issue links

For context, this was initially discussed in #33.

**Comment by greenknot** [comment]
Workaround: use a VNC password through `--vnc-password` (#36).

The VNC server has to be re-built (`make -C build/vnc/`).

**Comment by DCRichards** [comment]
Awesome, thanks for working on this!
