### ISSUE TITLE
OCR issue if element are not displayed from top to bottom

### ISSUE THREAD

**Issue by xchapron-ledger** [LedgerHQ/speculos#465]
Due to the current implementation of `EventsBroadcaster()` `broadcast()` method ( 
https://github.com/LedgerHQ/speculos/blob/b02412cccabff56e7034bb42745203da4ce7a4f4/speculos/api/events.py#L32)
The OCR content is reset based on the y coordinate. Enforcing drawing string from top to bottom if someone don't want to stumble upon a missing string in the OCR content.

This could be improve by resetting the OCR content when detecting a screen content reset (full rectangle draw).

**Comment by lpascal-ledger** [comment]
Quite a significant bug as it seem to be way more prevalent on Flex devices.
