### ISSUE TITLE
Update the provided app binaries

### ISSUE THREAD

**Issue by achow101** [LedgerHQ/speculos#85]
It would be nice to update  the provided app binaries so that people who are using this for CI can test against updated stuff.

Or is there some place that the apps can be downloaded?

**Comment by niooss-ledger** [comment]
Hello,
Right now, the applications that can be installed on Ledger devices are not publicly available. There are some discussions about making them available, and I do not have a clear view about when a decision will be made.

In the mean time, it is possible to build the application that are opensource, such as the Bitcoin one. This is what I did in PR #86 to update the provided apps. I built https://github.com/LedgerHQ/app-bitcoin/tree/nanos_1.4.2_2020-06-26_16-01-27 using the container from https://github.com/LedgerHQ/ledger-app-builder, with these commands:
```sh
podman run --rm -ti -v "$(realpath .):/app" ledgerhq/ledger-app-builder:1.6.0 make
cp bin/app.elf speculos/apps/nanos#btc#1.6#29717f9c.elf
make clean
podman run --rm -ti -v "$(realpath .):/app" ledgerhq/ledger-app-builder:1.6.0 make COIN=bitcoin_testnet
cp bin/app.elf speculos/apps/nanos#btc-test#1.6#29717f9c.elf
```

If I misunderstood your request, please provide more context about your use-case.
Thanks
